on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: AWS GITHUB-DOcKERHUB-EC2 Deploment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
       
    - name:  deploy to ec2
      uses: easingthemes/ssh-action@master
      env:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
         TARGET: ${ { secrets.TARGET_DIR }}
