on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: AWS GITHUB-DOCKERHUB-EC2 Deployment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
       
    - name:  deploy to ec2
      uses: easingthemes/ssh-deploy@master
      env:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        target: ${{ secrets.TARGET_DIR }}
