on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: AWS GITHUB-DOCKERHUB-EC2 Deployment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
       
    - name:  deploy to ec2
      uses: easingthemes/ssh-deploy@main
      env:
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        TARGET: ${{ secrets.TARGET_DIR }}
