name: Push-to-EC2

# Trigger deployment only on push to mai branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/github-Deployements"
          steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build, tag, and push the image to Docker Hub
      id: build-image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_REPOSITORY: "flask"
        IMAGE_TAG: "2"
      run: |
        # Build a docker container and push it to DCKERUB
        docker build -t $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to DOCKERHUB..."
        docker push $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG
        sudo docker pull surendrahari09/flask:2
          #Stop container
          sudo docker stop demoapp
          #Remove all untagged images
          sudo docker system  prune -a -f
          sudo docker run -d -p 5000:5000 --name demoapp -it surendrahari09/flask:2
